//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netline.Pdks.JP.Rnd.jpWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://customization.LogoPlatformTailor.com", ConfigurationName="jpWS.PntCardPortType")]
    public interface PntCardPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:upadatePntCard", ReplyAction="urn:upadatePntCardResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Netline.Pdks.JP.Rnd.jpWS.upadatePntCardResponse upadatePntCard(Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:upadatePntCard", ReplyAction="urn:upadatePntCardResponse")]
        System.Threading.Tasks.Task<Netline.Pdks.JP.Rnd.jpWS.upadatePntCardResponse> upadatePntCardAsync(Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="upadatePntCard", WrapperNamespace="http://customization.LogoPlatformTailor.com", IsWrapped=true)]
    public partial class upadatePntCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customization.LogoPlatformTailor.com", Order=0)]
        public int firm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customization.LogoPlatformTailor.com", Order=1)]
        public int period;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customization.LogoPlatformTailor.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string language;
        
        public upadatePntCardRequest() {
        }
        
        public upadatePntCardRequest(int firm, int period, string language) {
            this.firm = firm;
            this.period = period;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="upadatePntCardResponse", WrapperNamespace="http://customization.LogoPlatformTailor.com", IsWrapped=true)]
    public partial class upadatePntCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customization.LogoPlatformTailor.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object @return;
        
        public upadatePntCardResponse() {
        }
        
        public upadatePntCardResponse(object @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PntCardPortTypeChannel : Netline.Pdks.JP.Rnd.jpWS.PntCardPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PntCardPortTypeClient : System.ServiceModel.ClientBase<Netline.Pdks.JP.Rnd.jpWS.PntCardPortType>, Netline.Pdks.JP.Rnd.jpWS.PntCardPortType {
        
        public PntCardPortTypeClient() {
        }
        
        public PntCardPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PntCardPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PntCardPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PntCardPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Netline.Pdks.JP.Rnd.jpWS.upadatePntCardResponse Netline.Pdks.JP.Rnd.jpWS.PntCardPortType.upadatePntCard(Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest request) {
            return base.Channel.upadatePntCard(request);
        }
        
        public object upadatePntCard(int firm, int period, string language) {
            Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest inValue = new Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest();
            inValue.firm = firm;
            inValue.period = period;
            inValue.language = language;
            Netline.Pdks.JP.Rnd.jpWS.upadatePntCardResponse retVal = ((Netline.Pdks.JP.Rnd.jpWS.PntCardPortType)(this)).upadatePntCard(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Netline.Pdks.JP.Rnd.jpWS.upadatePntCardResponse> Netline.Pdks.JP.Rnd.jpWS.PntCardPortType.upadatePntCardAsync(Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest request) {
            return base.Channel.upadatePntCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<Netline.Pdks.JP.Rnd.jpWS.upadatePntCardResponse> upadatePntCardAsync(int firm, int period, string language) {
            Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest inValue = new Netline.Pdks.JP.Rnd.jpWS.upadatePntCardRequest();
            inValue.firm = firm;
            inValue.period = period;
            inValue.language = language;
            return ((Netline.Pdks.JP.Rnd.jpWS.PntCardPortType)(this)).upadatePntCardAsync(inValue);
        }
    }
}
