//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Netline.Pdks.JP.Rnd.pntCard {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PntCardSoap11Binding", Namespace="http://customization.LogoPlatformTailor.com")]
    public partial class PntCard : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback upadatePntCardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PntCard() {
            this.Url = global::Netline.Pdks.JP.Rnd.Properties.Settings.Default.Netline_Pdks_JP_Rnd_pntCard_PntCard;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event upadatePntCardCompletedEventHandler upadatePntCardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:upadatePntCard", RequestNamespace="http://customization.LogoPlatformTailor.com", ResponseNamespace="http://customization.LogoPlatformTailor.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string upadatePntCard(int firm, [System.Xml.Serialization.XmlIgnoreAttribute()] bool firmSpecified, int period, [System.Xml.Serialization.XmlIgnoreAttribute()] bool periodSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string language) {
            object[] results = this.Invoke("upadatePntCard", new object[] {
                        firm,
                        firmSpecified,
                        period,
                        periodSpecified,
                        language});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void upadatePntCardAsync(int firm, bool firmSpecified, int period, bool periodSpecified, string language) {
            this.upadatePntCardAsync(firm, firmSpecified, period, periodSpecified, language, null);
        }
        
        /// <remarks/>
        public void upadatePntCardAsync(int firm, bool firmSpecified, int period, bool periodSpecified, string language, object userState) {
            if ((this.upadatePntCardOperationCompleted == null)) {
                this.upadatePntCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupadatePntCardOperationCompleted);
            }
            this.InvokeAsync("upadatePntCard", new object[] {
                        firm,
                        firmSpecified,
                        period,
                        periodSpecified,
                        language}, this.upadatePntCardOperationCompleted, userState);
        }
        
        private void OnupadatePntCardOperationCompleted(object arg) {
            if ((this.upadatePntCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.upadatePntCardCompleted(this, new upadatePntCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void upadatePntCardCompletedEventHandler(object sender, upadatePntCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class upadatePntCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal upadatePntCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591